"""Core events module — defines all event types flowing through the system."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class EventType(str, Enum):
    """Enumeration of all event types in the trading system."""

    MARKET_DATA = "market_data"
    SIGNAL = "signal"
    ORDER = "order"
    FILL = "fill"
    PORTFOLIO = "portfolio"
    ALERT = "alert"
    ERROR = "error"
    HEARTBEAT = "heartbeat"


class SignalSide(str, Enum):
    """Signal direction."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class OrderType(str, Enum):
    """Order type."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class OrderStatus(str, Enum):
    """Order lifecycle status."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class AlertLevel(str, Enum):
    """Alert severity level."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


def _generate_id() -> str:
    """Generate a unique event ID."""
    return str(uuid.uuid4())


def _utc_now() -> datetime:
    """Generate current UTC timestamp."""
    return datetime.now(timezone.utc)


@dataclass(frozen=True)
class Event:
    """Base event class. All events are immutable."""

    event_type: EventType
    event_id: str = field(default_factory=_generate_id)
    timestamp: datetime = field(default_factory=_utc_now)
    source: str = ""


@dataclass(frozen=True)
class MarketDataEvent(Event):
    """Market data tick or bar event."""

    event_type: EventType = field(default=EventType.MARKET_DATA, init=False)
    symbol: str = ""
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: float = 0.0
    timeframe: str = "1m"
    exchange: str = ""
    raw_data: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class SignalEvent(Event):
    """Trading signal generated by a strategy."""

    event_type: EventType = field(default=EventType.SIGNAL, init=False)
    symbol: str = ""
    side: SignalSide = SignalSide.HOLD
    strength: float = 0.0  # Signal confidence 0.0 - 1.0
    strategy_name: str = ""
    reason: str = ""
    suggested_price: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class OrderEvent(Event):
    """Order to be placed with a broker."""

    event_type: EventType = field(default=EventType.ORDER, init=False)
    symbol: str = ""
    side: SignalSide = SignalSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    price: float | None = None
    stop_price: float | None = None
    status: OrderStatus = OrderStatus.PENDING
    broker_order_id: str = ""
    signal_id: str = ""  # Reference to originating signal


@dataclass(frozen=True)
class FillEvent(Event):
    """Order fill confirmation from broker."""

    event_type: EventType = field(default=EventType.FILL, init=False)
    symbol: str = ""
    side: SignalSide = SignalSide.BUY
    quantity: float = 0.0
    fill_price: float = 0.0
    commission: float = 0.0
    order_id: str = ""
    broker_order_id: str = ""


@dataclass(frozen=True)
class PortfolioEvent(Event):
    """Portfolio state update."""

    event_type: EventType = field(default=EventType.PORTFOLIO, init=False)
    total_value: float = 0.0
    cash: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    daily_pnl: float = 0.0
    positions: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AlertEvent(Event):
    """Alert/notification event."""

    event_type: EventType = field(default=EventType.ALERT, init=False)
    level: AlertLevel = AlertLevel.INFO
    title: str = ""
    message: str = ""
    channel: str = ""  # telegram, email, all


@dataclass(frozen=True)
class ErrorEvent(Event):
    """Error event for system failures."""

    event_type: EventType = field(default=EventType.ERROR, init=False)
    error_type: str = ""
    message: str = ""
    traceback: str = ""
    component: str = ""


@dataclass(frozen=True)
class HeartbeatEvent(Event):
    """System heartbeat for health monitoring."""

    event_type: EventType = field(default=EventType.HEARTBEAT, init=False)
    component: str = ""
    status: str = "healthy"
    details: dict[str, Any] = field(default_factory=dict)
