"""Core events module — defines all event types flowing through the system."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class EventType(StrEnum):
    """Enumeration of all event types in the trading system."""

    MARKET_DATA = "market_data"
    SIGNAL = "signal"
    ORDER = "order"
    FILL = "fill"
    PORTFOLIO = "portfolio"
    ALERT = "alert"
    ERROR = "error"
    HEARTBEAT = "heartbeat"
    ORDERBOOK = "orderbook"
    FUNDING_RATE = "funding_rate"


class SignalSide(StrEnum):
    """Signal direction."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class OrderType(StrEnum):
    """Order type."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class OrderStatus(StrEnum):
    """Order lifecycle status."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class AlertLevel(StrEnum):
    """Alert severity level."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


def _generate_id() -> str:
    """Generate a unique event ID."""
    return str(uuid.uuid4())


def _utc_now() -> datetime:
    """Generate current UTC timestamp."""
    return datetime.now(UTC)


@dataclass(frozen=True)
class Event:
    """Base event class. All events are immutable."""

    event_type: EventType
    event_id: str = field(default_factory=_generate_id)
    timestamp: datetime = field(default_factory=_utc_now)
    source: str = ""


@dataclass(frozen=True)
class MarketDataEvent(Event):
    """Market data tick or bar event."""

    event_type: EventType = field(default=EventType.MARKET_DATA, init=False)
    symbol: str = ""
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: float = 0.0
    timeframe: str = "1m"
    exchange: str = ""
    raw_data: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class OrderBookEvent(Event):
    """Represents a snapshot of the L2 Order Book."""
    event_type: EventType = field(default=EventType.ORDERBOOK, init=False)
    symbol: str = ""
    exchange: str = ""
    bids: list[list[float]] = field(default_factory=list)  # [[price, amount], ...]
    asks: list[list[float]] = field(default_factory=list)  # [[price, amount], ...]


@dataclass(frozen=True)
class FundingRateEvent(Event):
    """Represents the current funding rate for a perpetual contract."""
    event_type: EventType = field(default=EventType.FUNDING_RATE, init=False)
    symbol: str = ""
    exchange: str = ""
    funding_rate: float = 0.0
    next_funding_timestamp: int | None = None


@dataclass(frozen=True)
class SignalEvent(Event):
    """
    Represents a trading signal generated by a strategy.
    Enhanced to support the Advanced Analysis Engine output payload.
    """

    event_type: EventType = field(default=EventType.SIGNAL, init=False)
    symbol: str = ""
    side: SignalSide = SignalSide.HOLD
    strength: float = 0.0
    strategy_name: str = ""
    reason: str | None = None
    
    # Advanced Engine Fields
    confidence: float | None = None  # 0 to 100
    trend: str | None = None         # BULLISH, BEARISH, NEUTRAL
    momentum: str | None = None      # STRONG, WEAK, DIVERGING
    volatility: str | None = None    # EXPANDING, COMPRESSING
    sentiment: float | None = None   # -100 to 100
    risk_score: float | None = None  # 0 to 100
    suggested_price: float | None = None  # aka entry
    stop_loss: float | None = None
    take_profit: float | None = None
    reasoning: list[str] | None = None
    
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError("Strength must be between 0.0 and 1.0")


@dataclass(frozen=True)
class OrderEvent(Event):
    """Order to be placed with a broker."""

    event_type: EventType = field(default=EventType.ORDER, init=False)
    symbol: str = ""
    side: SignalSide = SignalSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0
    price: float | None = None
    stop_price: float | None = None
    status: OrderStatus = OrderStatus.PENDING
    broker_order_id: str = ""
    signal_id: str = ""  # Reference to originating signal
    strategy_name: str = ""
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class FillEvent(Event):
    """Order fill confirmation from broker."""

    event_type: EventType = field(default=EventType.FILL, init=False)
    symbol: str = ""
    side: SignalSide = SignalSide.BUY
    quantity: float = 0.0
    fill_price: float = 0.0
    commission: float = 0.0
    order_id: str = ""
    broker_order_id: str = ""
    strategy_name: str = ""
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    realized_pnl: float = 0.0


@dataclass(frozen=True)
class PortfolioEvent(Event):
    """Portfolio state update."""

    event_type: EventType = field(default=EventType.PORTFOLIO, init=False)
    total_value: float = 0.0
    cash: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    daily_pnl: float = 0.0
    positions: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AlertEvent(Event):
    """Alert/notification event."""

    event_type: EventType = field(default=EventType.ALERT, init=False)
    level: AlertLevel = AlertLevel.INFO
    title: str = ""
    message: str = ""
    channel: str = ""  # telegram, email, all


@dataclass(frozen=True)
class ErrorEvent(Event):
    """Error event for system failures."""

    event_type: EventType = field(default=EventType.ERROR, init=False)
    error_type: str = ""
    message: str = ""
    traceback: str = ""
    component: str = ""


@dataclass(frozen=True)
class HeartbeatEvent(Event):
    """System heartbeat for health monitoring."""

    event_type: EventType = field(default=EventType.HEARTBEAT, init=False)
    component: str = ""
    status: str = "healthy"
    details: dict[str, Any] = field(default_factory=dict)
